name: Pipeline de Integração Contínua (CI)

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Analiza a qualidade do codigo-fonte e executa testes
  validacao-aplicacao:
    runs-on: ubuntu-latest
    steps:
      - name: Obter Codigo do Repositorio (Checkout)
        uses: actions/checkout@v3

      - name: Simular Analise de Linter
        run: |
          echo "=> Iniciando verificacao automatizada de padronizacao de codigo..."
          echo "[SUCCESS] Linter finalizado: Padrao de projeto mantido com sucesso."

      - name: Simular Testes Automatizados
        run: |
          echo "=> Rodando suite de testes automatizados integrados..."
          echo "[SUCCESS] 12 testes executados. 0 falhas encontradas."

  # Job 2: Valida a sintaxe e a formatacao do nosso codigo Terraform
  validacao-infraestrutura:
    runs-on: ubuntu-latest
    steps:
      - name: Obter Codigo do Repositorio (Checkout)
        uses: actions/checkout@v3

      - name: Configurar Ferramenta Terraform no Runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Verificar Formatacao do Codigo (Terraform Fmt)
        run: terraform fmt -check

      - name: Inicializacao Estrutural (Sem Backend Real)
        run: terraform init -backend=false

      - name: Validar Sintaxe dos Arquivos (Terraform Validate)
        run: terraform validate

  # Job 3: Realiza o empacotamento real da aplicacao utilizando o Docker
  build-conteiner:
    needs: [validacao-aplicacao, validacao-infraestrutura]
    runs-on: ubuntu-latest
    steps:
      - name: Obter Codigo do Repositorio (Checkout)
        uses: actions/checkout@v3

      - name: Executar Build Real da Imagem Docker
        run: |
          echo "=> Construindo artefato imutavel com Docker..."
          docker build -t minha-app-pucrs:${{ github.sha }} .
          echo "[SUCCESS] Imagem Docker gerada e testada localmente com sucesso."

  # Job 4: Simula a esteira de implantacao progressiva apos o sucesso de todas as validacoes
  deploy-ambientes:
    needs: build-conteiner
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ambiente: [DEV, TST, HOL, PRD]
    steps:
      - name: Simular Deploy Progressivo
        run: |
          echo "=> Iniciando processo de implantacao automatizada..."
          echo "[DEPLOY] Aplicacao implantada com total sucesso no ambiente de: ${{ matrix.ambiente }}"